blog_project/blog_app/urls.py
from django.urls import path
from . import views


app_name="blog_app"
urlpatterns = [
    path('',views.index, name='index'),
    path("post/<str:slug>",views.details,name="detail"),
    path("new_something_url",views.new_url_view,name="new_page_url"),
    path("old_url",views.old_url_redirect,name="old_url"),
    path("contact",views.contact_view, name='contact'),
    path("about", views.about, name="about")
    
]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("blog_app.urls")),
]

blog_project/blog_app/models.py
from django.db import models
from django.utils.text import slugify

# Category
class Category(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url = models.URLField(null= True)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)

    def save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        super().save(*args,**kwargs)


    def __str__(self):
        return self.title
    
class AboutUs(models.Model):
    content= models.TextField()

blog_project/blog_app/forms.py
from django import forms


class ContactForm(forms.Form):
    name=forms.CharField(label='Name', max_length=50,required=True)
    email=forms.EmailField(label='Email',required=True)
    message=forms.CharField(label='Message',required=True)

blog_project/blog_app/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse,Http404
from django.urls import reverse
import logging
from .models import Post
from django.core.paginator import Paginator
from .forms import ContactForm
from .models import AboutUs


# Static Demo Data
# posts=[
#         {'id':1,'title': 'post1','content': 'content of post1'},
#         {'id':2,'title': 'post2','content': 'content of post2'},
#         {'id':3,'title': 'post3','content': 'content of post3'},
#         {'id':4,'title': 'post4','content': 'content of post4'},
        
#     ]

# Create your views here.
def index(request):
    blog_title="Latest Posts"
    # Getting Data From Post models
    all_posts=Post.objects.all()
    # Paginate
    paginator=Paginator(all_posts,5)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)

    return render(request,'index.html',{'blog_title':blog_title,'page_obj':page_obj})
def details(request,slug):
    # Static Data
    # post= next((item for item in posts if item['id']==post_id),None)
    try:
        # Getting Data form model by post Id
        post = Post.objects.get(slug=slug)
        related_posts=Post.objects.filter(category=post.category).exclude(pk=post.id)
    except Post.DoesNotExist:
        raise Http404("Post doesnot exist")
    # 
    # logger.debug(f'post variable is {post}')
    return render(request,'detail.html',{'post':post,'related_posts':related_posts})
def old_url_redirect(request):
    return redirect(reverse("blog_app:new_page_url"))
def new_url_view(request):
    return HttpResponse("This is the new url")

def contact_view(request):
    if request.method=='POST':
        form=ContactForm(request.POST)
        name=request.POST.get('name')
        email=request.POST.get('email')
        message=request.POST.get('message')
        logger=logging.getLogger('TESTING')
        if form.is_valid():
            
            logger.debug(f'POST data is {form.cleaned_data['name']}{form.cleaned_data['email']} {form.cleaned_data['message']}')
            success_message="your form is submitted"
            # send email or save in database
        else:
          
          logger.debug("form validation failure")
        return render(request,'contact.html',{'form':form,'success_message':success_message})
            
    return render(request,'contact.html')

def about(request):
    about_content= AboutUs.objects.first().content
    return render(request,'about.html',{'about_content':about_content})

blog_project/blog_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid ">
        <h3>About Us</h3>
        <div class="d-flex gap-3 justify-content-center mt-5">
            <img src="https://picsum.photos/300/300" alt="">
            <div class="content">
                {{about_content}}
            </div>
            
        </div>
    </div>
   {% endblock %}

blog_project/blog_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{blog_title | default:"Document"}}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    {% comment %} Header {% endcomment %}
    {%  include 'includes/header.html'%}
    {% comment %} dynamic content {% endcomment %}
    {% block content %}
    {% endblock %}

    {% comment %} Footer {% endcomment %}
    {% include 'includes/footer.html' %}
    
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

blog_project/blog_app/templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid ">
        <div class="d-flex justify-content-center mt-5">
            <div class="d-flex gap-3 flex-column">
                <h3>Contact Form</h3>
                <!-- Error messages -->
                {%for field in form%}
                    {%if field.errors%} 
                        <div class="col-12">
                            <span class="fw-bold">{{field.label_tag}}</span>
                            {% for error in field.errors%}
                                <span class="text-danger">{{error}}</span>
                            {%endfor%}
                        </div>
                    {%endif%}
                {%endfor%}

                <!-- Success Message -->
                {% if success_message %}
                    <div class="alert alert-success" role="alert">
                        {{success_message}}
                    </div>
                {%endif%}
                <form method="post" class="row g-3">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" value="{{name}}" name="name">
                    </div>
                    <div class="col-md-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" value="{{email}}" id="email" name="email">
                    </div>
                    <div class="col-12">
                        <label for="message" class="form-label">Message</label>
                        <textarea class="form-control" id="message" value="{{message}}" name="message" rows="4"></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        
    </div>
    {% endblock %}
    

blog_project/blog_app/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid ">
    
    <div class="row">
        <div class="col-lg-8">
            <h1 class="mb-4">{{post.title}} <small style="font-size:18px;">({{post.category.name}})</small></h1>
            <p class="text-muted">Posted on {{post.created_at|date:"F j, Y"}}</p>
            <img src="{{post.img_url}}" class="img-fluid mb-4" alt="Blog Image">
            <p>{{post.content}}</p>
            
        </div>
        <div class="col-lg-4">
            <div class="card mt-3">
            <div class="card-body">
                <h5 class="card-title">Related Posts</h5>
                <ul class="list-unstyled">
                {% for related_posts in related_posts %}
                <li><a href="{% url 'blog_app:detail' slug=related_posts.slug %}">{{related_posts.title}}</a></li>
                {%endfor%}
                </ul>
            </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog_project/blog_app/templates/includes/footer.html
<footer class="bg-dark text-light p-3 fixed-bottom">
      <div class="col-4 d-flex justify-content-center align-items-center">
        <span class="text-light">© 2021 Company, Inc</span>
      </div>
    </footer>

blog_project/blog_app/templates/includes/header.html
<header class="p-3 bg-dark text-white">
      <div class="row">
        <div class="col">
          <a href='/' class="text-light text-decoration-none"><h3>Blog</h3></a>
        </div>
        <div class="col">
          <div class="d-flex justify-content-center gap-3">
            <a class="text-light text-decoration-none" href="/">Home</a>
            <a class="text-light text-decoration-none" href="/about">About</a>
            <a class="text-light text-decoration-none" href="/contact">Contact</a>
          </div>
        </div>
      </div>
    </header>

blog_project/blog_app/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
      <div class="row">
        <h2>{{blog_title | upper}}</h2>
      </div>
      <div class="row m-3">
        {% if page_obj %}
          {% for post in page_obj %}
          <div class="col-4 mb-4">
            <div class="card">
              <div class="card-body">
                <div class="row">
                  <div class="col-md-4">
                    <img
                      style="height:100px; width:300px;"
                      src="{{post.img_url}}"
                      class="img-fluid"
                      alt="..."
                    />
                  </div>
                  <div class="col-md-8">
                    <h5 class="card-title">{{post.title}}</h5>
                    <p class="card-text">
                    {{post.content|truncatechars:50}}
                    </p>
                    <div class="d-flex justify-content-between">
                      <a href="{% url 'blog_app:detail' slug=post.slug %}">Read More</a>
                      <a class="text-decoration-none text-dark fw-bold" href="#"
                        >{{post.category.name}}</a
                      >
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          
          <div class="col-12 my-3">
            {%if page_obj.has_other_pages %}
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                       {%if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo; first</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                        {%endif%}
                        <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}</span></li>
                        {%if page_obj.has_next%}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                <span aria-hidden="true">last &raquo;</span>
                            </a>
                        </li>
                        {%endif%}
                    </ul>
                </nav>

                
            </div>
             {%endif %}
            {% else %}
            <p> No posts available </p>
        {% endif %}
      </div>
      <div class="row"></div>
    </div>
    {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>